//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadlineManagementDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComfortComplianceDeadlineDBEntities1 : DbContext
    {
        public ComfortComplianceDeadlineDBEntities1()
            : base("name=ComfortComplianceDeadlineDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_FileType> tbl_FileType { get; set; }
        public virtual DbSet<tblBranch> tblBranches { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblFileCategory> tblFileCategories { get; set; }
        public virtual DbSet<tblFileUploaded> tblFileUploadeds { get; set; }
        public virtual DbSet<Vw_FileUploaded> Vw_FileUploaded { get; set; }
        public virtual DbSet<tblToUpload> tblToUploads { get; set; }
        public virtual DbSet<Vw_UploadedFileEdit> Vw_UploadedFileEdit { get; set; }
        public virtual DbSet<Vw_PendingFiles> Vw_PendingFiles { get; set; }
    }
}
