//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadlineManagementDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFileUploaded
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> Dateofentery { get; set; }
        public Nullable<int> Filuploaded_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
    }
}
