//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadlineManagementDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblToUpload
    {
        public int Id { get; set; }
        public int department_Id { get; set; }
        public int filetype_Id { get; set; }
    }
}
