//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadlineManagementDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_FileUploaded
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Dateofentery { get; set; }
        public string DepartmentName { get; set; }
        public string BranchName { get; set; }
        public string CompanyName { get; set; }
        public string FileTypeName { get; set; }
        public string FileCategoryName { get; set; }
        public string Path { get; set; }
    }
}
