//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadlineManagementDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_UploadedFileEdit
    {
        public int FileUploadedId { get; set; }
        public Nullable<System.DateTime> Dateofentery { get; set; }
        public string Path { get; set; }
        public Nullable<int> UploadToUploadId { get; set; }
        public int FileTypeId { get; set; }
        public int FileCategoryId { get; set; }
        public int DepartmentId { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
    }
}
